In [2]:
import pandas as pd
df = pd.read_csv("orders.csv")

In [12]:
df.columns

Index(['OrderID', ' CustomerName', ' Product', ' Category', ' Quantity',
       ' Price', ' OrderDate', ' Shipped', ' Country'],
      dtype='object')

In [18]:
(df[[" Country" , " Product"]])

      Country         Product
0         USA          Laptop
1      Canada        Keyboard
2          UK         T-Shirt
3         USA    Coffee Maker
4     Germany       Mouse Pad
5      France   Running Shoes
6         USA         Blender
7      Canada         Monitor
8          UK           Jeans
9     Germany       Desk Lamp
10     France          Webcam
11        USA           Socks
12     Canada         Toaster
13         UK  External Drive
14        USA         Sweater
15    Germany   Picture Frame
16     France      Smartwatch
17     Canada           Dress
18         UK      Headphones
19        USA          Pillow
20  Australia            Book

In [19]:
df.iloc[0]

OrderID                  1001
 CustomerName      John Smith
 Product               Laptop
 Category         Electronics
 Quantity                   1
 Price                 1200.0
 OrderDate         2024-06-01
 Shipped                  Yes
 Country                  USA
Name: 0, dtype: object

In [21]:
df[(df[" Category"] == " Electronics") & (df[" Country"] == "USA")]

Empty DataFrame
Columns: [OrderID,  CustomerName,  Product,  Category,  Quantity,  Price,  OrderDate,  Shipped,  Country]
Index: []

In [22]:
df[(df[" Category"] == " Electronics") | (df[" Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.00,2024-06-01,Yes,USA
3,1004,Emily Davis,Coffee Maker,Home Goods,1,89.99,2024-06-03,Yes,USA
6,1007,David Chen,Blender,Home Goods,1,55.50,2024-06-04,No,USA
11,1012,Maria Hernandez,Socks,Apparel,12,8.50,2024-06-07,Yes,USA
14,1015,Kevin Scott,Sweater,Apparel,2,65.00,2024-06-10,No,USA
19,1020,Ava Perez,Pillow,Home Goods,4,20.00,2024-06-14,Yes,USA

In [23]:
df[df[" Quantity"] != 2]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.00,2024-06-01,Yes,USA
2,1003,Robert Brown,T-Shirt,Apparel,5,25.00,2024-06-02,Yes,UK
3,1004,Emily Davis,Coffee Maker,Home Goods,1,89.99,2024-06-03,Yes,USA
4,1005,Michael Wilson,Mouse Pad,Electronics,10,10.00,2024-06-03,Yes,Germany
5,1006,Jessica Lee,Running Shoes,Apparel,1,110.00,2024-06-04,Yes,France
6,1007,David Chen,Blender,Home Goods,1,55.50,2024-06-04,No,USA
8,1009,Daniel Garcia,Jeans,Apparel,3,45.00,2024-06-05,Yes,UK
9,1010,Laura Rodriguez,Desk Lamp,Home Goods,1,35.00,2024-06-06,No,Germany
10,1011,James Lopez,Webcam,Electronics,4,49.99,2024-06-07,Yes,France
11,1012,Maria Hernandez,Socks,Apparel,12,8.50,2024-06-07,Yes,USA
12,1013,Thomas White,Toaster,Home Goods,1,39.99,2024-06-08,Yes,Canada
13,1014,Chloe King,External Drive,Electronics,1,85.00,2024-06-09,Yes,UK
15,1016,Olivia Green,Picture Frame,Home Goods,6,15.00,2024-06-11,Yes,Germany
16,1017,Ethan Hall,Smartwatch,Electronics,1,199.99,2024-06-12,Yes,France
17,1018,Isabella Baker,Dress,Apparel,1,79.99,2024-06-13,Yes,Canada
18,1019,Noah Adams,Headphones,Electronics,3,150.00,2024-06-13,No,UK
19,1020,Ava Perez,Pillow,Home Goods,4,20.00,2024-06-14,Yes,USA
20,1021,Ryan Clark,Book,Media,5,18.00,2024-06-14,Yes,Australia

In [24]:
df[df[" CustomerName"].str.startswith('J')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.00,2024-06-01,Yes,USA
5,1006,Jessica Lee,Running Shoes,Apparel,1,110.00,2024-06-04,Yes,France
10,1011,James Lopez,Webcam,Electronics,4,49.99,2024-06-07,Yes,France

In [25]:
df[df[" Country"].isin(["USA", "Germany"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Emily Davis,Coffee Maker,Home Goods,1,89.99,2024-06-03,Yes,USA
4,1005,Michael Wilson,Mouse Pad,Electronics,10,10.00,2024-06-03,Yes,Germany
6,1007,David Chen,Blender,Home Goods,1,55.50,2024-06-04,No,USA
9,1010,Laura Rodriguez,Desk Lamp,Home Goods,1,35.00,2024-06-06,No,Germany
11,1012,Maria Hernandez,Socks,Apparel,12,8.50,2024-06-07,Yes,USA
14,1015,Kevin Scott,Sweater,Apparel,2,65.00,2024-06-10,No,USA
15,1016,Olivia Green,Picture Frame,Home Goods,6,15.00,2024-06-11,Yes,Germany
19,1020,Ava Perez,Pillow,Home Goods,4,20.00,2024-06-14,Yes,USA

In [26]:
df[~df[" Country"].isin(["USA", "Germany"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.00,2024-06-01,Yes,USA
1,1002,Alice Johnson,Keyboard,Electronics,2,75.50,2024-06-01,No,Canada
2,1003,Robert Brown,T-Shirt,Apparel,5,25.00,2024-06-02,Yes,UK
5,1006,Jessica Lee,Running Shoes,Apparel,1,110.00,2024-06-04,Yes,France
7,1008,Sarah Miller,Monitor,Electronics,2,300.00,2024-06-05,Yes,Canada
8,1009,Daniel Garcia,Jeans,Apparel,3,45.00,2024-06-05,Yes,UK
10,1011,James Lopez,Webcam,Electronics,4,49.99,2024-06-07,Yes,France
12,1013,Thomas White,Toaster,Home Goods,1,39.99,2024-06-08,Yes,Canada
13,1014,Chloe King,External Drive,Electronics,1,85.00,2024-06-09,Yes,UK
16,1017,Ethan Hall,Smartwatch,Electronics,1,199.99,2024-06-12,Yes,France
17,1018,Isabella Baker,Dress,Apparel,1,79.99,2024-06-13,Yes,Canada
18,1019,Noah Adams,Headphones,Electronics,3,150.00,2024-06-13,No,UK
20,1021,Ryan Clark,Book,Media,5,18.00,2024-06-14,Yes,Australia

In [27]:
df.loc[df[' CustomerName'] == "John Smith", " Product"] = "Xbox"

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [29]:
df.loc[df[" Country"] == "USA", " Country"] = "United States"

In [31]:
df.loc[df[" Country"] == "United States"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Emily Davis,Coffee Maker,Home Goods,1,89.99,2024-06-03,Yes,United States
6,1007,David Chen,Blender,Home Goods,1,55.50,2024-06-04,No,United States
11,1012,Maria Hernandez,Socks,Apparel,12,8.50,2024-06-07,Yes,United States
14,1015,Kevin Scott,Sweater,Apparel,2,65.00,2024-06-10,No,United States
19,1020,Ava Perez,Pillow,Home Goods,4,20.00,2024-06-14,Yes,United States

In [ ]:
df[" Country"] = df[" Country"].str.upper()

In [32]:
df = df.drop(20)

In [33]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
15,1016,Olivia Green,Picture Frame,Home Goods,6,15.00,2024-06-11,Yes,Germany
16,1017,Ethan Hall,Smartwatch,Electronics,1,199.99,2024-06-12,Yes,France
17,1018,Isabella Baker,Dress,Apparel,1,79.99,2024-06-13,Yes,Canada
18,1019,Noah Adams,Headphones,Electronics,3,150.00,2024-06-13,No,UK
19,1020,Ava Perez,Pillow,Home Goods,4,20.00,2024-06-14,Yes,United States

In [ ]:
df.dropna()

In [35]:
df[" Country"].value_counts()

 Country
United States    5
Canada           4
UK               4
Germany          3
France           3
 USA             1
Name: count, dtype: int64

In [36]:
df.groupby(" Country")[" Price"].sum()

 Country
 USA             1200.00
Canada            495.48
France            359.98
Germany            60.00
UK                305.00
United States     238.99
Name:  Price, dtype: float64

In [37]:
df.sort_index(" Price", ascending=False)

TypeError: DataFrame.sort_index() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

In [38]:
df.to_csv("New.csv", index=False)